spring:
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/beyond?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    cn.tsxygfy.blog.*: info
  file: ./log/beyond-log.log
server:
  port: 8888
